name: Suppy Automation

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Save credentials.json
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

    - name: Run automation
      env:
        SUPPY_EMAIL: ${{ secrets.SUPPY_EMAIL }}
        SUPPY_PASSWORD: ${{ secrets.SUPPY_PASSWORD }}
        PARTNER_ID: ${{ secrets.PARTNER_ID }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py