name: Suppy Hourly Upload

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Allow manual triggering

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Suppy Upload Job
      env:
        SUPPY_EMAIL: ${{ secrets.SUPPY_EMAIL }}
        SUPPY_PASSWORD: ${{ secrets.SUPPY_PASSWORD }}
        PARTNER_ID: ${{ secrets.PARTNER_ID }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
      run: |
        python app.py run-job