name: Hourly Suppy Upload

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "SUPPY_EMAIL=${{ secrets.SUPPY_EMAIL }}" >> $GITHUB_ENV
          echo "SUPPY_PASSWORD=${{ secrets.SUPPY_PASSWORD }}" >> $GITHUB_ENV
          echo "PARTNER_ID=${{ secrets.PARTNER_ID }}" >> $GITHUB_ENV
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV
          echo "SHEET_NAME=${{ secrets.SHEET_NAME }}" >> $GITHUB_ENV
          echo "DASHBOARD_URL=${{ secrets.DASHBOARD_URL }}" >> $GITHUB_ENV

      - name: Run main.py
        run: python main.py